package:
  exclude:
    - '**/*'
  include:
    - node_modules/**
    - utils/**
    - user-management-service/**

service: vinyl-search-user-service

functions:
  user-management-service:
    handler: user-management-service/user-main.main
    name:  ${self:service}-${opt:stage}
    environment:
      MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
      user_pool_id: ${self:custom.config.user_pool_id}
    events:
      - http:
          method: post
          path: /
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: /
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: /records
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: /forum
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: /market
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: post
          path: /market/{postId}/sold
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: delete
          path: /records/{recordId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
