custom:
  config: ${file(./${opt:stage}.env.yml):config}
  env: ${file(./${opt:stage}.env.yml):env}

service: ${self:custom.config.service}

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage}
  region: ${self:custom.config.region}

package:
  # individually: true
  exclude:
    - '**/*'
  include:
    - node_modules/**
    - utils/**
    - records-management-service/**
    - userpool-trigger-service/**
    - user-management-service/**
    - forum-management-service/**
    - administration-service/**
    - market-service/**

functions:
  userpool-trigger-service:
    handler: userpool-trigger-service/user-pool-triggers.handler
    name:  ${self:service}-userpool-trigger-service-${opt:stage}
    environment:
      MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
      user_pool_id: ${self:custom.config.user_pool_id}
  forum-management-service:
    handler: forum-management-service/forum-main.main
    name:  ${self:service}-forum-management-service-${opt:stage}
    environment:
      MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
      BUCKET_NAME: ${self:custom.env.BUCKET_NAME}
      BUCKET_REGION: ${self:custom.env.BUCKET_REGION}
    events:
      - http:
          method: get
          path: forum/{postId}
          cors: true
      - http:
          method: get
          path: forum
          cors: true
      - http:
          method: get
          path: forum/search
          cors: true
      - http:
          method: post
          path: forum
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: post
          path: forum/{postId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: delete
          path: forum/{postId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
  administration-service:
    handler: administration-service/admin-main.main
    name:  ${self:service}-administration-service-${opt:stage}
    environment:
      MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
      user_pool_id: ${self:custom.config.user_pool_id}
      BUCKET_NAME: ${self:custom.env.BUCKET_NAME}
      BUCKET_REGION: ${self:custom.env.BUCKET_REGION}
    events:
      - http:
          method: get
          path: admin/users/{userUid}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: admin/admin-users
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: delete
          path: admin/admin-users/{userUid}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: post
          path: admin/admin-users/{userUid}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: admin/records
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: delete
          path: admin/records/{recordId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: admin/forum
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: delete
          path: admin/forum/{postId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
  user-management-service:
    handler: user-management-service/user-main.main
    name:  ${self:service}-user-management-service-${opt:stage}
    environment:
      MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
      user_pool_id: ${self:custom.config.user_pool_id}
    events:
      - http:
          method: post
          path: users
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: users
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: users/records
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: users/forum
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: delete
          path: users/records/{recordId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}

  records-management-service:
    handler: records-management-service/records-main.main
    name:  ${self:service}-records-management-service-${opt:stage}
    environment:
      MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
      BUCKET_NAME: ${self:custom.env.BUCKET_NAME}
      BUCKET_REGION: ${self:custom.env.BUCKET_REGION}
    events:
      - http:
          method: get
          path: records
          cors: true
      - http:
          method: get
          path: records/search
          cors: true
      - http:
          method: get
          path: records/{recordId}
          cors: true
      - http:
          method: post
          path: records
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: post
          path: records/{recordId}
          cors: true
          authorizer:
            name: vinyl-authorizer
            arn:  ${self:custom.config.userpool_authorizer_arn}
      - http:
          method: get
          path: records/{recordId}/revisions
          cors: true
      - http:
          method: get
          path: records/{recordId}/revisions/{revisionId}
          cors: true
  market-management-service:
      handler: market-service/market-main.main
      name:  ${self:service}-market-service-${opt:stage}
      environment:
        MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
        BUCKET_NAME: ${self:custom.env.BUCKET_NAME}
        BUCKET_REGION: ${self:custom.env.BUCKET_REGION}
      events:
        - http:
            method: get
            path: market
            cors: true
        - http:
            method: post
            path: market
            cors: true
            authorizer:
              name: vinyl-authorizer
              arn:  ${self:custom.config.userpool_authorizer_arn}


